# Whether to enable all default rules.
default: true

# MD007/ul-indent: Unordered list indentation.
MD007:
  # Spaces for indent.
  indent: 4

# MD013/line-length: Line length.
MD013: false

# MD025/single-title/single-h1: Multiple top-level headings in the same document.
MD025: false

# MD033/no-inline-html: Inline HTML.
MD033: false

# MD050/strong-style: Strong style.
MD050:
  #   style: "consistent"
  style: "asterisk"
