project:
  id: d9baa4a0-b76f-4217-ab6a-0cf9bc644151
  name: 'DS ML Project: Flight Delay Prediction'
  description: >-
    Analysis of the Tunisair Flight Delay Duration data set, including a predictive model using on a CatBoost regressor
  authors:
    - name: Kvn Dtrx
      mail: kvn.dtrx+git@protonmail.ch
  license:
    type: MIT
    year: 2025
    file: LICENSE.txt
forges:
  github:
    url: https://github.com/kvn-dtrx/ds-ml-project_flight-delay-prediction
    visibility: public
