repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: detect-aws-credentials # Example: Detect AWS secrets in code

    - repo: https://github.com/psf/black
      rev: 22.10.0
      hooks:
          - id: black # Code formatter for Python

    - repo: https://github.com/PyCQA/flake8
      rev: 6.0.0
      hooks:
          - id: flake8 # Python linting

    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v8.36.0
      hooks:
          - id: eslint # Linter for JavaScript and TypeScript

    - repo: local
      hooks:
          - id: custom-hook
            name: Custom Hook
            entry: ./scripts/custom-script.sh # Path to your script
            language: script
            files: .* # Apply to all files
